# Generated by Django 4.2.8 on 2024-07-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Здравоохранение', 'verbose_name_plural': 'Здравоохранение'},
        ),
        migrations.AddField(
            model_name='hospital',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_data', to='nathprojects.graph'),
        ),
    ]
