# Generated by Django 4.2.8 on 2024-07-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0002_graph_alter_hospital_options_hospital_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='graph',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
