# Generated by Django 4.2.8 on 2024-07-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0003_remove_hospital_graph_delete_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
    ]
