# Generated by Django 4.2.8 on 2024-08-20 16:21

from django.db import migrations, models
import nathprojects.models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0003_study_csv_file_delete_studydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographics',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AddField(
            model_name='demographics',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=nathprojects.models.csv_upload_to, verbose_name='CSV файл'),
        ),
        migrations.DeleteModel(
            name='DemographicsData',
        ),
    ]
