# Generated by Django 4.2.8 on 2024-07-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0004_hospital_description_hospital_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
