# Generated by Django 4.2.8 on 2024-08-20 16:56

from django.db import migrations, models
import nathprojects.models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0005_alter_demographics_options_culture_csv_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': 'Дороги', 'verbose_name_plural': 'Дороги'},
        ),
        migrations.AddField(
            model_name='road',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=nathprojects.models.csv_upload_to, verbose_name='CSV файл'),
        ),
        migrations.DeleteModel(
            name='RoadData',
        ),
    ]
