# Generated by Django 4.2.8 on 2024-07-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0005_hospital_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='year',
        ),
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='nathprojects.hospital')),
            ],
            options={
                'verbose_name': 'Данные по смертности',
                'verbose_name_plural': 'Данные по смертности',
            },
        ),
    ]
