# Generated by Django 4.2.8 on 2024-07-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0006_remove_hospital_deaths_remove_hospital_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaldata',
            options={'ordering': ['hospital'], 'verbose_name': 'Данные по смертности', 'verbose_name_plural': 'Данные по смертности'},
        ),
    ]
