# Generated by Django 4.2.8 on 2024-08-21 09:31

from django.db import migrations, models
import nathprojects.models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0006_alter_road_options_road_csv_file_delete_roaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=nathprojects.models.csv_upload_to, verbose_name='CSV файл'),
        ),
        migrations.DeleteModel(
            name='ScienceData',
        ),
    ]
