# Generated by Django 4.2.8 on 2024-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0008_study_studydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='region',
            field=models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область')], max_length=50, verbose_name='Регион'),
        ),
    ]
