# Generated by Django 4.2.8 on 2024-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0009_hospital_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='region',
        ),
        migrations.AddField(
            model_name='hospitaldata',
            name='region',
            field=models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область')], max_length=50, verbose_name='Регион'),
        ),
    ]
