# Generated by Django 4.2.8 on 2024-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0010_remove_hospital_region_hospitaldata_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydata',
            name='region',
            field=models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область')], max_length=50, verbose_name='Регион'),
        ),
    ]
