# Generated by Django 4.2.8 on 2024-07-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0011_studydata_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Демография',
                'verbose_name_plural': 'Демографию',
            },
        ),
        migrations.CreateModel(
            name='DemographicsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('index', models.IntegerField()),
                ('region', models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область')], max_length=50, verbose_name='Регион')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='nathprojects.demographics')),
            ],
            options={
                'verbose_name': 'Данные по демографии',
                'verbose_name_plural': 'Данные по демографии',
                'ordering': ['name'],
            },
        ),
    ]
