# Generated by Django 4.2.8 on 2024-08-21 13:01

from django.db import migrations, models
import nathprojects.models


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0013_labour_csv_file_delete_labourdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='econom',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=nathprojects.models.csv_upload_to, verbose_name='CSV файл'),
        ),
        migrations.DeleteModel(
            name='EconomData',
        ),
    ]
