# Generated by Django 4.2.8 on 2024-07-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nathprojects', '0013_alter_demographics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культура',
            },
        ),
        migrations.AlterField(
            model_name='demographicsdata',
            name='region',
            field=models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область'), ('spb', 'Санкт-Петербург'), ('saratov', 'Саратовская область'), ('novosibirsk', 'Новосибирская область'), ('yekaterinburg', 'Свердловская область'), ('krasnodar', 'Краснодарский край'), ('kazan', 'Республика Татарстан'), ('vladivostok', 'Приморский край'), ('krasnodar', 'Краснодарский край'), ('nizhny_novgorod', 'Нижегородская область'), ('rostov', 'Ростовская область')], max_length=50, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='hospitaldata',
            name='region',
            field=models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область'), ('spb', 'Санкт-Петербург'), ('saratov', 'Саратовская область'), ('novosibirsk', 'Новосибирская область'), ('yekaterinburg', 'Свердловская область'), ('krasnodar', 'Краснодарский край'), ('kazan', 'Республика Татарстан'), ('vladivostok', 'Приморский край'), ('krasnodar', 'Краснодарский край'), ('nizhny_novgorod', 'Нижегородская область'), ('rostov', 'Ростовская область')], max_length=50, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='studydata',
            name='region',
            field=models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область'), ('spb', 'Санкт-Петербург'), ('saratov', 'Саратовская область'), ('novosibirsk', 'Новосибирская область'), ('yekaterinburg', 'Свердловская область'), ('krasnodar', 'Краснодарский край'), ('kazan', 'Республика Татарстан'), ('vladivostok', 'Приморский край'), ('krasnodar', 'Краснодарский край'), ('nizhny_novgorod', 'Нижегородская область'), ('rostov', 'Ростовская область')], max_length=50, verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='CultureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('people', models.FloatField()),
                ('region', models.CharField(blank=True, choices=[('tula', 'Тульская область'), ('moscow', 'Московская область'), ('spb', 'Санкт-Петербург'), ('saratov', 'Саратовская область'), ('novosibirsk', 'Новосибирская область'), ('yekaterinburg', 'Свердловская область'), ('krasnodar', 'Краснодарский край'), ('kazan', 'Республика Татарстан'), ('vladivostok', 'Приморский край'), ('krasnodar', 'Краснодарский край'), ('nizhny_novgorod', 'Нижегородская область'), ('rostov', 'Ростовская область')], max_length=50, verbose_name='Регион')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='nathprojects.culture')),
            ],
            options={
                'verbose_name': 'Данные по культуре',
                'verbose_name_plural': 'Данные по культуре',
                'ordering': ['name'],
            },
        ),
    ]
