# Generated by Django 4.2.8 on 2024-07-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='address',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
        migrations.RemoveField(
            model_name='category',
            name='map_html',
        ),
        migrations.RemoveField(
            model_name='category',
            name='phone',
        ),
    ]
