# Generated by Django 4.2.8 on 2024-07-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_category_address_remove_category_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=28, verbose_name='Название записи'),
        ),
    ]
